"""empty message

Revision ID: ad6f66bc2081
Revises: 34cc6f7b2992
Create Date: 2021-08-03 02:03:11.708669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6f66bc2081'
down_revision = '34cc6f7b2992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pokemon', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pokemon', type_='foreignkey')
    op.drop_column('pokemon', 'user_id')
    # ### end Alembic commands ###
